---
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
tables: yes
---

```{r config, warning=FALSE, echo=FALSE, message=FALSE}
# Options default dos chuncks
knitr::opts_chunk$set(
  message = FALSE,
  echo = FALSE,
  warning = FALSE,
  cache = TRUE,
  fig.pos = "H",
  fig.align = "center",
  fig.height = 7,
  fig.width = 9,
  fig.caption =  TRUE
)

# Options xtable
options(xtable.comment = FALSE,
        xtable.table.placement = "H",
        knitr.kable.NA = "",
        scipen = 3)
```

```{r biblioteca}
# Bibliotecas
library(knitr)
library(kableExtra)
library(ggplot2)
library(ltm)
library(irtoys)
```

```{r data}
# Respondentes
resp <- read.csv2("data.csv", na.strings =  "")

# Gabarito
gab <- read.csv2("gab.csv",  head = FALSE)

# Fatores associados
fatores <- resp[, 27:29]

fatores.cols <- names(fatores)
fatores.cols <- gsub("[.]", " ", fatores.cols)
fatores.cols <- paste0(fatores.cols, "?")

colnames(fatores) <- paste0("X", 1:3)

fatores$X1 <- forcats::fct_infreq(fatores$X1)
fatores$X2 <- forcats::fct_infreq(fatores$X2)
fatores$X3 <- forcats::fct_infreq(fatores$X3)

# Itens
resp <- resp[, 1:26]

# Renomeia os itens
colnames(resp) <- paste0("i", 1:26)
colnames(gab) <- paste0("i", 1:26)
```

O presente trabalho é fruto dos esforços da turma do 1º semestre de 2018
do curso de Teorias de Avaliação ministrada pelo professor
[Adilson dos Anjos]().
